version: 2.1

aliases:
  - &parameters
    parameters:
      pyenv_python_version:
        type: string
        default: ">unspecified<"
      python_version:
        type: string
      toxenv:
        type: string

  - &py35_arguments
      name: py35
      pyenv_python_version: "3.5.6"
      python_version: "3.5"
      toxenv: "py35"

  - &py36_arguments
      name: py36
      pyenv_python_version: "3.6.7"
      python_version: "3.6"
      toxenv: "py36"

  - &py37_arguments
      name: py37
      pyenv_python_version: "3.7.1"
      python_version: "3.7"
      toxenv: "py37"

  - &dist_arguments
      <<: *py37_arguments
      toxenv: "dist"

commands:
  run_prepare:
    steps:
      - run:
          name: Prepare
          command: |
            python3 --version
            python3 -m pip --version
            python3 -m pip install -q --user --ignore-installed --upgrade virtualenv
            python3 -m virtualenv venv
            venv/bin/python -m pip install --upgrade pip
            venv/bin/python -m pip freeze
            venv/bin/python --version
            venv/bin/pip --version
            venv/bin/pip install tox

  run_test:
    steps:
      - run:
          name: Test
          command: |
            venv/bin/tox
      - run:
          name: Codecov
          command: |
            venv/bin/tox -e codecov

  store_dist:
    steps:
      - store_artifacts:
          path: dist/


executors:
  linux_executor:
    <<: *parameters
    docker:
      - image: circleci/python:<< parameters.python_version >>
    environment:
      TOXENV: << parameters.toxenv >>

  osx_executor:
    <<: *parameters
    macos:
      xcode: "10.0.0"
    environment:
      TOXENV: << parameters.toxenv >>
      PATH: "~/.pyenv/shims:$PATH"


jobs:
  linux:
    <<: *parameters
    executor:
      name: linux_executor
      python_version: << parameters.python_version >>
      toxenv: << parameters.toxenv >>
    steps:
      - checkout
      - run_prepare
      - run_test
      - store_dist

  osx:
    <<: *parameters
    executor:
      name: osx_executor
      python_version: << parameters.python_version >>
      toxenv: << parameters.toxenv >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - brew_pyenv-<< parameters.pyenv_python_version >>
      - run:
          name: OSX Prepare
          command: |
            brew install readline xz pyenv
            pyenv install --skip-existing << parameters.pyenv_python_version >>
            pyenv global << parameters.pyenv_python_version >>
      - save_cache:
          key: brew_pyenv-<< parameters.pyenv_python_version >>
          paths:
            - "~/.pyenv"
            - "/usr/local/Homebrew"
      - run_prepare
      - run_test
      - store_dist


workflows:
  version: 2

  all:
    jobs:
      - linux:
          name: linux-dist
          <<: *dist_arguments
      - linux:
          name: linux-py35
          <<: *py35_arguments
      - linux:
          name: linux-py36
          <<: *py36_arguments
      - linux:
          name: linux-py37
          <<: *py37_arguments
      - osx:
          name: osx-dist
          <<: *dist_arguments
      - osx:
          name: osx-py35
          <<: *py35_arguments
      - osx:
          name: osx-py36
          <<: *py36_arguments
      - osx:
          name: osx-py37
          <<: *py37_arguments
